part of '../error.dart';

class ErrorMessagesX {
  static String getMessage(int errorCode) {
    return _errorMessages[errorCode] ?? _errorMessages[ErrorCodesX.unexpected]!;
  }

  static final Map<int, String> _errorMessages = {
  ErrorCodesX.unexpected: 'An unexpected error occurred. Please try again later.',
  ErrorCodesX.vpnRequired: 'VPN connection required. Please connect and try again.',
  ErrorCodesX.vpnMustBeEnabled: 'VPN must be enabled. Activate it and retry.',
  ErrorCodesX.noInternetConnection: 'No internet connection. Check your network settings.',
  ErrorCodesX.invalidURL: 'Invalid URL. Please check and try again.',
  ErrorCodesX.multipleChoices: 'Multiple choices available. Please select one.',
  ErrorCodesX.movedPermanently: 'Resource moved permanently. Update your URL.',
  ErrorCodesX.found: 'Resource found at a different location.',
  ErrorCodesX.seeOther: 'See other location for the resource.',
  ErrorCodesX.notModified: 'Resource not modified since last request.',
  ErrorCodesX.useProxy: 'Proxy required for access. Configure and retry.',
  ErrorCodesX.temporaryRedirect: 'Temporary redirect. Follow the new location.',
  ErrorCodesX.permanentRedirect: 'Permanent redirect. Update your links.',
  ErrorCodesX.badRequest: 'Bad request. Check the request and try again.',
  ErrorCodesX.unauthorized: 'Unauthorized access. Check your credentials.',
  ErrorCodesX.forbidden: 'Access forbidden. You do not have permission.',
  ErrorCodesX.notFound: 'Resource not found. Verify the URL.',
  ErrorCodesX.methodNotAllowed: 'Method not allowed for this resource.',
  ErrorCodesX.notAcceptable: 'Not acceptable. Adjust your request.',
  ErrorCodesX.requestTimeout: 'Request timed out. Try again later.',
  ErrorCodesX.conflict: 'Request conflict. Resolve the issue and retry.',
  ErrorCodesX.gone: 'Resource is gone. It has been permanently removed.',
  ErrorCodesX.lengthRequired: 'Content length required. Include it and try again.',
  ErrorCodesX.preconditionFailed: 'Precondition failed. Review and resubmit.',
  ErrorCodesX.payloadTooLarge: 'Payload too large. Reduce size and try again.',
  ErrorCodesX.uriTooLong: 'URI too long. Shorten it and retry.',
  ErrorCodesX.unsupportedMediaType: 'Unsupported media type. Check your request.',
  ErrorCodesX.rangeNotSatisfiable: 'Range not satisfiable. Adjust your request.',
  ErrorCodesX.expectationFailed: 'Expectation failed. Review the request and try again.',
  ErrorCodesX.imATeapot: 'I’m a teapot. This request cannot be processed.',
  ErrorCodesX.misdirectedRequest: 'Misdirected request. Verify the endpoint.',
  ErrorCodesX.unprocessableEntity: 'Unprocessable entity. Check the request data.',
  ErrorCodesX.locked: 'Resource is locked. Try again later.',
  ErrorCodesX.failedDependency: 'Failed dependency. Resolve issues and retry.',
  ErrorCodesX.upgradeRequired: 'Upgrade required. Update your system.',
  ErrorCodesX.preconditionRequired: 'Precondition required. Check your request.',
  ErrorCodesX.tooManyRequests: 'Too many requests. Try again later.',
  ErrorCodesX.requestHeaderFieldsTooLarge: 'Request header fields too large.',
  ErrorCodesX.unavailableForLegalReasons: 'Unavailable for legal reasons.',
  ErrorCodesX.internalServerError: 'Internal server error. Please try again later.',
  ErrorCodesX.notImplemented: 'Not implemented. Feature is not available.',
  ErrorCodesX.badGateway: 'Bad gateway. Check the server and retry.',
  ErrorCodesX.serviceUnavailable: 'Service unavailable. Try again later.',
  ErrorCodesX.gatewayTimeout: 'Gateway timeout. The server took too long to respond.',
  ErrorCodesX.httpVersionNotSupported: 'HTTP version not supported. Upgrade your client.',
  ErrorCodesX.variantAlsoNegotiates: 'Variant also negotiates. Check your request.',
  ErrorCodesX.insufficientStorage: 'Insufficient storage. Free up space and retry.',
  ErrorCodesX.loopDetected: 'Loop detected. Resolve the loop and try again.',
  ErrorCodesX.notExtended: 'Not extended. Further extensions required.',
  ErrorCodesX.networkAuthenticationRequired: 'Network authentication required. Authenticate and retry.',
  };
}